### ISSUE TITLE
Multiple plugs require IP addresses

### ISSUE THREAD

**Issue by codetheweb** [codetheweb/homebridge-tuya-outlet#17]

**Comment by BufferOverflowed** [comment]
For some reason, when I add two outlets appending the ip to each in the config, Homebridge gets stuck on “updating” accessories. When I only have one outlet with no ip set in the config, is when Homebridge works normally. Not sure if maybe a recent update to the plugin/Homebridge/node version might have introduced this bug, but I figured I’d mention it. Thanks for your hard work!

**Comment by codetheweb** [comment]
Yep, this is a known issue.  See #4, specifically [this comment](https://github.com/codetheweb/homebridge-tuya-outlet/issues/4#issuecomment-361977715).

**Comment by codetheweb** [comment]
Hey @RIPv1 I've published a new package that fixes many issues, including making Homebridge crash if your device isn't plugged in.  It also includes an easier setup process.

Please move to [homebridge-tuya](https://www.npmjs.com/package/homebridge-tuya) instead of continuing to use this package.
