### ISSUE TITLE
Cannot bind tuna outlet

### ISSUE THREAD

**Issue by xxavarlon87** [codetheweb/homebridge-tuya-outlet#20]
Hi,

I tried to get a tuya outlet accessory in my home bridge setup. I sniff all the keys (devId and localKey) and picked up the local ip of my outlet from my router and put it in my config.json

{
			"accessory": "TuyaOutlet",
			"name": "Kleine Vitrine",
			"devId": "xxxxxxx",
			"localKey": "xxxxx",
			"ip": "192.168.2.121"
}

Restart the home bridge service, everything looks fine, but HomeKit tells me all the time "Update" an every item in HomeKit (include the outlet) and then "No Response" on every device.
I cannot find any error or exception in the log. All I can find is:

Jun  8 19:18:25 raspberrypi homebridge[981]: [8.6.2018, 19:18:25] [Kleine Vitrine] Initializing TuyaOutlet accessory...
Jun  8 19:18:25 raspberrypi homebridge[981]: 2018-06-08T17:18:25.359Z TuyAPI Device(s):
Jun  8 19:18:25 raspberrypi homebridge[981]: 2018-06-08T17:18:25.380Z TuyAPI [ { type: 'outlet',
Jun  8 19:18:25 raspberrypi homebridge[981]:     ip: '192.168.2.126',
Jun  8 19:18:25 raspberrypi homebridge[981]:     id: 'xxxxx', -> Dont want to show my ids
Jun  8 19:18:25 raspberrypi homebridge[981]:     key: 'xxxxxx',
Jun  8 19:18:25 raspberrypi homebridge[981]:     uid: '',
Jun  8 19:18:25 raspberrypi homebridge[981]:     port: 6668,
Jun  8 19:18:25 raspberrypi homebridge[981]:     version: 3.1,
Jun  8 19:18:25 raspberrypi homebridge[981]:     cipher:
Jun  8 19:18:25 raspberrypi homebridge[981]:      { algorithm: [Object],
Jun  8 19:18:25 raspberrypi homebridge[981]:        mode: [Object],
Jun  8 19:18:25 raspberrypi homebridge[981]:        blockSize: 16,
Jun  8 19:18:25 raspberrypi homebridge[981]:        _finish: false,
Jun  8 19:18:25 raspberrypi homebridge[981]:        _input: null,
Jun  8 19:18:25 raspberrypi homebridge[981]:        output: null,
Jun  8 19:18:25 raspberrypi homebridge[981]:        _op: [Function],
Jun  8 19:18:25 raspberrypi homebridge[981]:        _decrypt: false } } ]

AND:

Jun  8 19:18:38 raspberrypi homebridge[981]: 2018-06-08T17:18:38.589Z homebridge-tuya Getting device status...
Jun  8 19:18:38 raspberrypi homebridge[981]: 2018-06-08T17:18:38.592Z TuyAPI Payload:
Jun  8 19:18:38 raspberrypi homebridge[981]: 2018-06-08T17:18:38.595Z TuyAPI { gwId: 'xxxxxx', devId: 'xxxxxxx' }
Jun  8 19:18:38 raspberrypi homebridge[981]: 2018-06-08T17:18:38.598Z TuyAPI Sending this data:  000055aa000000000000000a000000467b2267774964223a223033323030323934363030313934373839376435222c226465764964223a223033323030323934363030313934373839376435227d000000000000aa55

Thats all. I think he doesn't get any response from the tuna cloud, but I'm not sure. What ist the problem?

And yes I closed the tuya app on my phone and double checked the ids.

Thanks

**Comment by codetheweb** [comment]
Sorry, but I can't really help.  It looks like your device isn't responding to status probe requests.

You might want to try directly running [tuyapi](https://github.com/codetheweb/tuyapi) to further debug the issue.

Is the computer Homebridge is running on able to ping your Tuya device?
