### ISSUE TITLE
Not sure what this error means, but my outlet stopped responding.

### ISSUE THREAD

**Issue by socalcal** [codetheweb/homebridge-tuya-outlet#21]
Have been using the outlet and plugin for awhile, but recently ran into some unresponsiveness.  I haven't had a chance to investigate until now and not sure if this has something to do with MacOS updates or not.  Here's the output when I run Homebridge.  It doesn't kick the error out immediately, but perhaps when the outlet is polled.  Any help appreciated.  Thanks!

`/usr/local/lib/node_modules/homebridge-tuya-outlet/node_modules/tuyapi/index.js:282
      client.write(buffer);
            ^

TypeError: Cannot read property 'write' of null
    at retryConnect.to (/usr/local/lib/node_modules/homebridge-tuya-outlet/node_modules/tuyapi/index.js:282:13)
    at Socket.handleError (/usr/local/lib/node_modules/homebridge-tuya-outlet/node_modules/net-retry-connect/index.js:21:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by codetheweb** [comment]
I need more detail to help you.  Can you please start Homebridge with `DEBUG=* homebridge` and post the output?  Thanks.

**Comment by socalcal** [comment]
Homebridge appears to crash when the tuya outlet is polled.  I have both the tuya-outlet and tuyapi-extended plugins installed.  Not sure if that's the problem, but here's the output with some of the identifying accessory info x'd out:

`[6/11/2018, 8:13:46 PM] Loaded config.json with 1 accessories and 1 platforms.
[6/11/2018, 8:13:46 PM] ---
[6/11/2018, 8:13:46 PM] Loaded plugin: homebridge-chamberlain
[6/11/2018, 8:13:46 PM] Registering accessory 'homebridge-chamberlain.Chamberlain'
[6/11/2018, 8:13:46 PM] ---
[6/11/2018, 8:13:46 PM] Loaded plugin: homebridge-platform-myq
[6/11/2018, 8:13:46 PM] Registering platform 'homebridge-platform-myq.MyQ'
[6/11/2018, 8:13:46 PM] ---
[6/11/2018, 8:13:46 PM] Loaded plugin: homebridge-tuya-outlet
[6/11/2018, 8:13:46 PM] Registering accessory 'homebridge-tuya-outlet.TuyaOutlet'
[6/11/2018, 8:13:46 PM] ---
[6/11/2018, 8:13:47 PM] Loaded plugin: homebridge-tuyapi-extended
[6/11/2018, 8:13:47 PM] ---
[6/11/2018, 8:13:47 PM] Loading 1 platforms...
[6/11/2018, 8:13:47 PM] [MyQ Platform] Initializing MyQ platform...
[6/11/2018, 8:13:47 PM] Loading 1 accessories...
[6/11/2018, 8:13:47 PM] [Tuya Outlet] Initializing TuyaOutlet accessory...
  TuyAPI Device(s):  +0ms
  TuyAPI [ { type: 'outlet',
  TuyAPI     id: '03200379dc4fxxxxxxxx',
  TuyAPI     key: 'xxxxxxxxxxxxxxxx',
  TuyAPI     uid: '',
  TuyAPI     port: 6668,
  TuyAPI     version: 3.1,
  TuyAPI     cipher: 
  TuyAPI      { algorithm: [Object],
  TuyAPI        mode: [Object],
  TuyAPI        blockSize: 16,
  TuyAPI        _finish: false,
  TuyAPI        _input: null,
  TuyAPI        output: null,
  TuyAPI        _op: [Function],
  TuyAPI        _decrypt: false } } ] +0ms
[6/11/2018, 8:13:47 PM] [MyQ Platform] found GarageDoorOpener, deviceid=xxxxxxxx
[6/11/2018, 8:13:47 PM] [MyQ Platform] found Light Device, deviceid=xxxxxxxx
[6/11/2018, 8:13:47 PM] [MyQ Platform] Initializing platform accessory 'Garage Door'...
[6/11/2018, 8:13:47 PM] [MyQ Platform] Initializing platform accessory 'Living Room'...
  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +4ms
Setup Payload:
X-HM://0023ISYWY1L39
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  EventedHTTPServer Server listening on port 57960 +35ms
[6/11/2018, 8:13:47 PM] Homebridge is running on port 57960.
  EventedHTTPServer [::ffff:10.0.1.9] New connection from client +15s
  EventedHTTPServer [::ffff:10.0.1.9] HTTP server listening on port 57961 +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /pair-setup +8ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pair-setup +1ms
  HAPServer [40:6C:8F:02:8D:96] Pair step 1/5 +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +176ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /pair-setup +148ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pair-setup +0ms
  HAPServer [40:6C:8F:02:8D:96] Pair step 2/5 +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +158ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /pair-setup +30ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pair-setup +1ms
  HAPServer [40:6C:8F:02:8D:96] Pair step 3/5 +0ms
  HAPServer [40:6C:8F:02:8D:96] Pair step 4/5 +8ms
  HAPServer [40:6C:8F:02:8D:96] Pair step 5/5 +2ms
  Accessory [Homebridge] Paired with client 45410065-4759-4DD6-9FAB-3F97BC7CA09B +2ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:10.0.1.9] Client connection closed +136ms
  EventedHTTPServer [::ffff:10.0.1.9] New connection from client +2ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP server listening on port 57963 +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP server was closed +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /pair-verify +5ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pair-verify +0ms
  HAPServer [40:6C:8F:02:8D:96] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /pair-verify +19ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pair-verify +0ms
  HAPServer [40:6C:8F:02:8D:96] Pair verify step 2/2 +1ms
  HAPServer [40:6C:8F:02:8D:96] Client 45410065-4759-4DD6-9FAB-3F97BC7CA09B verification complete +2ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /accessories +133ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +335ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true}] +2ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /pairings +1s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pairings +0ms
  HAPServer [40:6C:8F:02:8D:96] Adding pairing info for client +2ms
  Accessory [Homebridge] Paired with client 7E5386B4-B83D-4EBD-AEF6-919E29499555 +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +2s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":10,"ev":true},{"aid":2,"iid":11,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Outlet In Use" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +5ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":10,"ev":true},{"aid":2,"iid":11,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Outlet In Use" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +5ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +9ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +6ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":12,"ev":true}] +3ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Target Door State" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Obstruction Detected" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +4ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":12,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Target Door State" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Obstruction Detected" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.109] New connection from client +785ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP server listening on port 57965 +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /pair-verify +7ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pair-verify +1ms
  HAPServer [40:6C:8F:02:8D:96] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /pair-verify +10ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: POST /pair-verify +0ms
  HAPServer [40:6C:8F:02:8D:96] Pair verify step 2/2 +1ms
  HAPServer [40:6C:8F:02:8D:96] Client 45410065-4759-4DD6-9FAB-3F97BC7CA09B verification complete +1ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /accessories +5ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /characteristics +222ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +2ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Target Door State" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /characteristics +5ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /characteristics +5ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Target Door State" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +2s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":1,"iid":2,"value":true}] +0ms
  Accessory [Homebridge] Setting Characteristic "Identify" to value true +0ms
  Accessory [Homebridge] Identification request +1ms
  Accessory [Homebridge] Identification request ignored; no listeners to 'identify' event +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=3.11,3.10,3.12 +8s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /characteristics?id=3.11,3.10,3.12 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Target Door State" +2ms
  Accessory [Homebridge] Got Characteristic "Target Door State" value: 1 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Current Door State" +1ms
  Accessory [Homebridge] Got Characteristic "Current Door State" value: 1 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Obstruction Detected" +0ms
  Accessory [Homebridge] Got Characteristic "Obstruction Detected" value: false +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +442ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":2,"value":true}] +2ms
  Accessory [Homebridge] Setting Characteristic "Identify" to value true +0ms
  Accessory [Garage Door] Identification request +0ms
  Accessory [Garage Door] Identification request ignored; no listeners to 'identify' event +4ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=3.11,3.10,3.12 +1s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /characteristics?id=3.11,3.10,3.12 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Target Door State" +1ms
  Accessory [Homebridge] Got Characteristic "Target Door State" value: 1 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Current Door State" +1ms
  Accessory [Homebridge] Got Characteristic "Current Door State" value: 1 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Obstruction Detected" +0ms
  Accessory [Homebridge] Got Characteristic "Obstruction Detected" value: false +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /characteristics +214ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /characteristics +6ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":12,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Target Door State" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Obstruction Detected" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /characteristics +7ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":10,"ev":true},{"aid":2,"iid":11,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Outlet In Use" for events +0ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=3.11,3.10,3.12 +1s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /characteristics?id=3.11,3.10,3.12 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Target Door State" +1ms
  Accessory [Homebridge] Got Characteristic "Target Door State" value: 1 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Current Door State" +0ms
  Accessory [Homebridge] Got Characteristic "Current Door State" value: 1 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Obstruction Detected" +0ms
  Accessory [Homebridge] Got Characteristic "Obstruction Detected" value: false +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=4.10 +2s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /characteristics?id=4.10 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +1ms
  Accessory [Homebridge] Got Characteristic "On" value: true +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +496ms
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":2,"value":true}] +0ms
  Accessory [Homebridge] Setting Characteristic "Identify" to value true +0ms
  Accessory [Living Room] Identification request +0ms
  Accessory [Living Room] Identification request ignored; no listeners to 'identify' event +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=4.10 +2s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /characteristics?id=4.10 +1ms
  Accessory [Homebridge] Getting value for Characteristic "On" +1ms
  Accessory [Homebridge] Got Characteristic "On" value: true +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=4.10 +1s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /characteristics?id=4.10 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +1ms
  Accessory [Homebridge] Got Characteristic "On" value: true +0ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=2.10 +2s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: GET /characteristics?id=2.10 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +1ms
  homebridge-tuya Getting device status... +0ms
  TuyAPI Payload:  +40s
  TuyAPI { gwId: '03200379dc4fxxxxxxxx', devId: '03200379dc4fxxxxxxxx' } +0ms
  TuyAPI Sending this data:  000055aa000000000000000a000000467b2267774964223a223033323030333739646334663232633332336334222c226465764964223a223033323030333739646334663232633332336334227d000000000000aa55 +2ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP request: /characteristics +27s
  HAPServer [40:6C:8F:02:8D:96] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.109] HTTP Response is finished +0ms
/usr/local/lib/node_modules/homebridge-tuya-outlet/node_modules/tuyapi/index.js:282
      client.write(buffer);
            ^

TypeError: Cannot read property 'write' of null
    at retryConnect.to (/usr/local/lib/node_modules/homebridge-tuya-outlet/node_modules/tuyapi/index.js:282:13)
    at Socket.handleError (/usr/local/lib/node_modules/homebridge-tuya-outlet/node_modules/net-retry-connect/index.js:21:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by codetheweb** [comment]
(Tip: to format multi-line code segments with Markdown, use triple backticks (```) rather than a single backtick.)

Sorry for the late reply.

It looks like your device may not have an IP - which usually means that `resolveIds()` timed out / erred.  There's a better version of `resolveIds()` in the pipeline for `tuyapi` that will be included in the next major version, but for now try passing in the IP directly to your Homebridge configuration file and see if that fixes the issue.

**Comment by socalcal** [comment]
Sorry about the code formatting.  I just selected the "Insert code" icon at the top of the message box and was wondering why it didn't look like the code I had seen in other messages.

I added the IP to the config.json file and it still crashes in the same manner.  I don't need to modify the plugins themselves, right?

Thanks for your help.

**Comment by codetheweb** [comment]
Hmm.

Update to the latest version with `npm update -g homebridge-tuya-outlet`.  Then run `npm list homebridge-tuya-outlet -g`.  The version number should be 1.1.3.

**Comment by socalcal** [comment]
Okay, I updated to the latest version and still crashing.  FYI, since I added the ip and updated to the latest version, the crash occurs when adding the tuya outlet to homekit.  First homebridge is added as an accessory, then the chamberlain accessories, then when it get to the tuya outlet, homebridge crashes.

**Comment by codetheweb** [comment]
Can you please make sure you don't have the app open on your phone?  Also, try pinging the IP address of your device from the computer that's running Homebridge just to make sure it's reachable.

If the output of `DEBUG=* homebridge` has changed since last time, please also post that.

**Comment by socalcal** [comment]
I think I know what the problem is if you're mentioning to not have the app (I'm assuming Jinvoo or Tuya) running on my phone.  I have another home running the same plugin, but both outlets are registered under the same Jinvoo username.  That outlet seems to work fine, but the one local to me does not.  My plan is to register the outlets under location-specific usernames and see if that solves the problem.  I probably won't be able to get to it until August, though, but I'll return and post my results.  Thanks for all your help!

**Comment by codetheweb** [comment]
Hey @socalcal I've published a new package that fixes many issues, including making Homebridge crash if your device isn't plugged in.  It also includes an easier setup process.

Please move to [homebridge-tuya](https://www.npmjs.com/package/homebridge-tuya) instead of continuing to use this package.

If you continue to have problems, please open an issue in that repo.
