### ISSUE TITLE
Easier way to setup?

### ISSUE THREAD

**Issue by Kazom** [codetheweb/homebridge-tuya-outlet#23]
I've been looking through the API and all your previous comments but I'm still not sure  where "devId" and "localKey" are located. I tried to sniff the traffic to find it with no luck. I'm registered as a dev on Tuya but I'm still lost on how to get this information for my plugs.

**Comment by Crocy1104** [comment]
Found the devId in the "device information" on the Jinvoo Smart App. But I don't really have a plan how to get the localKey..

**Comment by codetheweb** [comment]
Sorry @Kazom, didn't see this issue until now.  There will be an easier way to register a device in the future, but for now please see [these instructions](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md)

**Comment by codetheweb** [comment]
@Kazom @Crocy1104 please move to the new [homebridge-tuya](https://www.npmjs.com/package/homebridge-tuya) package.  It includes a much easier way to set things up.
