### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by RuairiOliver** [codetheweb/homebridge-tuya-outlet#3]
Hi,

Thanks for this plugin.

I followed the instructions but I just get a timeout on home bridge.

"accessories": [
      {
        "accessory": "TuyaOutlet",
        "name": "Sitting Lamp",
        "ip": "IP_CAPTURED_FROM_CHARLES,
        "id": "ID_FROM_CHARLES",
        "localKey": "LOCAL_KEY_FROM_CHARLES"
      }
    ],

{ Error: connect ETIMEDOUT IP_FROM_CHARLES:6668

Any idea?

Thanks

**Comment by codetheweb** [comment]
I published version 2.0 of TuyAPI a few weeks ago, which included numerous breaking changes.

I just updated `homebridge-tuya-outlet` to work with v2 of TuyAPI, so try doing `sudo npm install -g homebridge-tuya-outlet` and it should work now.

**Comment by RuairiOliver** [comment]
Thanks, the error is gone now but the device is just stuck on updating in the home app on iOS. I can't turn it on or off

**Comment by RuairiOliver** [comment]
All of my requests have only m.device.list with the same data pretty much in each. I don't have any request with m.dev.list

**Comment by RuairiOliver** [comment]
I tested with your TuyAPI directly and I can turn the socket on and off from the command line so that's something anyway

**Comment by RuairiOliver** [comment]
Using a combination of CMD2 and your TuyAPI it's working from me with Siri and the Home app so I'm sorted, thanks!
