### ISSUE TITLE
Error comunicating with device

### ISSUE THREAD

**Issue by francisco-navarro** [codetheweb/homebridge-tuya-outlet#8]
Everything works perfect when I reboot the device. But after a few hours, this always happens to me:

Accessory [Homebridge] Got Characteristic "On" value: undefined
Accessory [Homebridge] Error getting value for Characteristic "On": Error communicating with device. Make sure nothing else is trying to control it or connected to it.
EventedHTTPServer [::ffff:XXXXXXXX] HTTP Response is finished

I don't have any other applications o device connected. 
Could be improved the communication so is not always broken after a few hours?

**Comment by codetheweb** [comment]
This is a known issue with TuyAPI, and unfortunately isn't that easy to solve.  Sorry I can't help more.

If you have ideas for improvement, feel free to open an issue over at [TuyAPI](https://github.com/codetheweb/tuyapi/issues).
