### ISSUE TITLE
localid...... 

### ISSUE THREAD

**Issue by ldhall1856** [codetheweb/homebridge-tuya-outlet#9]
I didn't want to seem like a totally idiot.... but i guess i am....  I can't find the localkey anywhere.....

I'm not good at coding so i'm sure its something i don't know....  sorry for my Ignorants......

**Comment by codetheweb** [comment]
Sorry, but it's currently not exactly trivial to get the `localKey`.  Having said that, the instructions for doing so are fairly comprehensive and can be found [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md).
